version: '2'

services:
  db:
    restart: always
    image: mariadb:11.6
    mem_limit: 256M
    volumes:
      - NEXTCLOUD_MARIADB:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=secret
      - TZ=Europe/Zurich

  nextcloud:
    restart: always
    image: quay.io/rootlogin/nextcloud:latest
    read_only: true
    build:
      context: .
    container_name: nextcloud
    mem_limit: 1G
    volumes:
      - nextcloud_data:/data
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

volumes:
  nextcloud_data:
