name: "Ubuntu 24.04 Runner: Build & Push Container Image"

on:
  push:
    branches:
      - main
    paths:
      - 'ubuntu-runner/24.04.Dockerfile'
      - '.github/workflows/build-container.yml'
      - 'build-ubuntu-runner-24.04.yml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build & Push
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: ubuntu-runner
      dockerfile: 24.04.Dockerfile
      tag: 24.04
      latest: true
      push: true
      push-docker: false
      push-quay: false
      architectures: '["amd64"]'
    secrets: inherit