name: "MCPO: Build & Publish Container Image"

on:
  push:
    branches:
      - main
    paths:
      - '../../.archive/mcpo/**'
      - '.github/workflows/build-container.yml'
      - 'build-mcpo.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      mcpo: ${{ steps.mcpo_version.outputs.MCPO_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Extract MCPO_VERSION from Dockerfile
        id: mcpo_version
        run: |
          echo "MCPO_VERSION=$(grep -E '^ARG MCPO_VERSION=' mcpo/Dockerfile | cut -d '=' -f 2 | tr -d '"')" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build & Push
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "mcpo"
      dockerfile: "Dockerfile"
      tag: ${{ needs.get-version.outputs.mcpo }}
      push: true
      push-docker: false
      push-quay: true
      latest: true
    secrets: inherit