services:
  freshrss:
    image: ghcr.io/erhardtconsulting/freshrss
    build:
      context: .
    container_name: freshrss
    user: "2000:2000"
    environment:
      - TZ=Europe/Zurich
    volumes:
      - freshrss_data:/opt/freshrss/data
    ports:
      - "8080:80"
    tmpfs:
      - /tmp:uid=2000,gid=2000,mode=0755
      - /run:exec,uid=2000,gid=2000,mode=0755

volumes:
  freshrss_data: