services:
  freshrss:
    image: quay.io/erhardtconsulting/freshrss
    read_only: true
    build:
      context: .
    container_name: freshrss
    user: "65534:65534"
    environment:
      - TZ=Europe/Zurich
    volumes:
      - freshrss_data:/opt/freshrss/data
    ports:
      - "8080:8080"
    tmpfs:
      - /tmp:uid=65534,gid=65534,mode=0755

volumes:
  freshrss_data: