name: "Ubuntu 24.04 Runner: Build Container Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ubuntu-runner/24.04.Dockerfile'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-ubuntu-runner-24.04-pr.yml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build & Push
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: ubuntu-runner
      dockerfile: 24.04.Dockerfile
      tag: 24.04
      latest: true
      push: false
      push-docker: false
      push-quay: false
      architectures: '["amd64"]'
    secrets: inherit