name: "Gatus: Build Container Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'gatus/Dockerfile'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-gatus-pr.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      gatus: ${{ steps.gatus_version.outputs.GATUS_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Extract GATUS_VERSION from Dockerfile
        id: gatus_version
        run: |
          GATUS_VERSION=$(grep -E '^ARG GATUS_VERSION=' gatus/Dockerfile | cut -d '=' -f 2 | tr -d '"')
          echo "GATUS_VERSION=$GATUS_VERSION" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "gatus"
      dockerfile: "Dockerfile"
      tag: ${{ needs.get-version.outputs.gatus }}
      push: false
      push-docker: false
      push-quay: false
    secrets: inherit