name: "Init-Postgres 16: Build Container Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'init-postgres/pg16.Dockerfile'
      - 'init-postgres/root/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-init-postgres-16-pr.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      postgresql: ${{ steps.postgresql_version.outputs.POSTGRESQL_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Get PostgreSQL version
        id: postgresql_version
        run: |
          echo "POSTGRESQL_VERSION=$(./get-apt-version.sh http://apt.postgresql.org bookworm-pgdg postgresql-client-16 | sed -E 's/^([0-9]+\.[0-9]+).*$/\1/')" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "init-postgres"
      dockerfile: "pg16.Dockerfile"
      tag: ${{ needs.get-version.outputs.postgresql }}
      push: false
      push-docker: false
      push-quay: false
      use-swap: true
    secrets: inherit