name: "Node-RED: Build Container Image / Pull Request"

on:
  push:
    branches:
      - main
    paths:
      - 'nodered/Dockerfile'
      - 'nodered/root/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-nodered-pr.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      nodered: ${{ steps.nodered_version.outputs.NODERED_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Get nodered version
        id: nodered_version
        run: |
          echo "NODERED_VERSION=$(grep -oE '\"node-red\": \"(\w*.\w*.\w*.\w*.\w*.)' nodered/package.json | cut -d\" -f4)" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@ea5e3101575c020574dcbdb75c1d7efc9e411e21 # main
    with:
      image: "nodered"
      dockerfile: "Dockerfile"
      tag: ${{ needs.get-version.outputs.nodered }}
      push: false
      push-quay: false
      push-docker: false
    secrets: inherit