name: "Init-Postgres 16: Build Container Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'init-postgres/pg16.Dockerfile'
      - 'init-postgres/root/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-init-postgres-16-pr.yml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "init-postgres"
      dockerfile: "pg16.Dockerfile"
      version: "16"
      push: false