name: "Python 3.13.x: Build & Push Container Image"

on:
  push:
    branches:
      - main
    paths:
      - 'base-python/3.13.Dockerfile'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-base-python-3.13.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      python: ${{ steps.python_version.outputs.PYTHON_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Get Python version
        id: python_version
        run: |
          echo "PYTHON_VERSION=$(grep -E '^FROM docker.io/library/python:[0-9]+\.[0-9]+\.[0-9]+' base-python/3.13.Dockerfile | sed -E 's|.*python:([0-9]+\.[0-9]+\.[0-9]+).*|\1|')" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build & Push
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "base-python"
      dockerfile: "3.13.Dockerfile"
      tag: ${{ needs.get-version.outputs.python }}
      latest: false
      push: true
      push-docker: false
      push-quay: false
    secrets: inherit