name: "ArgoCD: Build Container Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'argocd/**'
      - '.github/workflows/build-argocd-pr.yml'
      - '.github/workflows/build-container.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      argocd: ${{ steps.argocd-version.outputs.ARGOCD_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Extract ARGOCD_VERSION from Dockerfile
        id: argocd-version
        run: |
          ARGOCD_VERSION=$(grep -E '^FROM quay.io/argoproj/argocd:v[0-9]+\.[0-9]+\.[0-9]+' argocd/Dockerfile | sed -E 's|.*argocd:v([0-9]+\.[0-9]+\.[0-9]+).*|\1|')
          echo "ARGOCD_VERSION=$ARGOCD_VERSION" >> $GITHUB_OUTPUT

  call-build-workflow:
    name: Build & Push
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "argocd"
      dockerfile: "Dockerfile"
      tag: ${{ needs.get-version.outputs.argocd }}
      push: false
      push-docker: false
      push-quay: false
    secrets: inherit