name: "Init-Postgres: Build Docker Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'init-postgres/**'

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "init-postgres"

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU for multi-architecture build
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
        with:
          install: true

      - name: Extract PG_CLIENT_VERSION from Dockerfile
        id: vars
        run: |
          PG_CLIENT_VERSION=$(grep -E '^ARG PG_CLIENT_VERSION=' init-postgres/Dockerfile | cut -d '=' -f 2 | tr -d '"')
          echo "PG_CLIENT_VERSION=$PG_CLIENT_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6
        with:
          context: init-postgres
          platforms: "linux/386,linux/amd64,linux/arm64,linux/arm/v7"
          push: false
          tags: |
            ghcr.io/erhardtconsulting/${{ env.IMAGE_NAME }}:dev-${{ env.PG_CLIENT_VERSION }}