name: "Renovate: Build Container Image / Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'renovate/Dockerfile'
      - 'renovate/root/**'
      - '.github/workflows/build-container.yml'
      - '.github/workflows/build-renovate-pr.yml'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      renovate: ${{ steps.renovate_version.outputs.RENOVATE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Get renovate version
        id: renovate_version
        run: |
          echo "RENOVATE_VERSION=$(grep -E '^FROM docker.io/renovate/renovate:[0-9]+\.[0-9]+\.[0-9]+' renovate/Dockerfile | cut -d ':' -f 2 | tr -d '@sha256')" >> $GITHUB_OUTPUT
  call-build-workflow:
    name: Build
    needs: get-version
    uses: erhardtconsulting/images/.github/workflows/build-container.yml@main
    with:
      image: "renovate"
      dockerfile: "Dockerfile"
      tag: ${{ needs.get-version.outputs.renovate }}
      push: false
      push-docker: false
      push-quay: false
    secrets: inherit