name: "Init-Postgres: Build & Push Container Image"

on:
  push:
    branches:
      - main
    paths:
      - 'init-postgres/**'
      - '.github/workflows/build-init-postgres.yml'

permissions:
  contents: read
  packages: write

jobs:
  call-build-workflow:
    name: Build & Push Base
    uses: erhardtconsulting/images/.github/workflows/build-container.yaml@main
    with:
      image: base
      version: "16"
      push: true