name: Renovate merge notification
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.actor == 'erhardt-consulting-bot'
    steps:
      - name: Send pushover notification
        run: |-
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_API_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            --form-string "title=Renovate Update" \
            --form-string "html=1" \
            --form-string "message=<b>${{ github.repository }}</b><br><br>${{ github.event.head_commit.message }}<br><a href='${{ github.event.head_commit.url }}'>Open Commit</a>" \
            https://api.pushover.net/1/messages.json
